# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nyun2xcnFT6WRv4wl-cbjiV_xk2bCfH2
"""

print("Hello everyone")

print('Hi')

print("pussy cat","pussy cat")
print("where have you been")

print("pussy cat","pussy cat",sep="**",end="    ")
print("where have you been")

a=3
b=5
print(a+b)

type(a)

type(3.2)

type(True)



"""Code explaining all the data types supoorted by python
bool takes only True and False
"""

type('true')

type(2)

type(3.2)

type('hi')

type(True)

type(False)

type(false)

print(type(False))

print(type(1000))

print(1,00,000)

c=10+5j
print(type(c),c)

b1=True
b2=False
b3=10>5
print(type(b1),b1,b2,b3)



"""All the data types supoorted by python:int,float,str,bool,complex"""

a=3 
print(a)
f=3
print(f)

#Variable names should not be keywords,it should not start with digit,only special symbol allowed is _
#4fgh=2 is error
#abc@d=3
abc_d=3
print(abc_d)
a=3
print(a)

#Multiple assignment in single statement
x,y,z=10,5.97,True
print(x,y,z)
print(type(x))

sum=counter=avg=0
print(sum,counter,avg)

#Python is dynamically type language
a=2.89
print(type(a))
a=False
print(type(a))

# Divsion (float) '/'  Floor Division='//',% gives u remainder
a=3
b=2
print(a+b)
print(a*b)
print(a-b)
print(a**b)
print(a/b)
print(a//b)
print(a%b)

x,y=10,2.6
print(x+y)

s1,s2="hello","good morning"
s3=s1+s2
print(s3)

#Order of operations PEDMAS Paranthesis,Exponentiation,Multiplication,Division,Addition,Subtraction
print(2*(3-1))
print(2**1+1)
print(3*1**3)

# * operator works for strings
first="hello"
second="hi"
print(second*first)

#float to int
x=10.89
y=int(x)
print(type(x),type(y))
print(x,y)

#int to float
x=10
y=float(x)
print(type(x),type(y))
print(x,y)

#float to complex
x=10.5
y=complex(x)
print(type(x),type(y))
print(x,y)

#complex to float is not allowed
c=10-5j
f=float(c)
print(type(c),type(f))
print(c,f)

#string to int
s='123'
s1='123a'
print(type(s),s)
i=int(s)
i1=int(s1)
print(type(i),i)
print(type(i1),i1)

b1=10>5
print(b1)

x,y,z=0,20.78,"hello"
s=""
print(bool(x))
print(bool(y))
print(bool(z))
print(bool(s))

a=int(input("enter value of a"))
b=int(input("enter value of b"))
c=a+b
print(c)

x=int(input("enter value of x "))
y=int(input("enter value of y"))
temp,x=x,y
y=temp

print(x,y)

